// Tables to export (order matters for foreign key dependencies)
export const TABLES_TO_EXPORT = [
  'projects', 
  'cbs_codes',
  'user_roles',
  'farms',
  'fields',
  'operation_types',
  'fuel_equipment',
  'fuel_tanks',
  'implements',
  'inventory_items',
  'employees',
  'payroll_periods',
  'employee_benefits',
  'employee_documents',
  'employee_incidents',
  'employee_salary_history',
  'employee_vacations',
  'employee_loans',
  'employee_timesheets',
  'period_employee_benefits',
  'day_labor_entries',
  'day_labor_attachments',
  'transactions',
  'transaction_attachments',
  'transaction_edits',
  'fuel_transactions',
  'pending_fuel_submissions',
  'tractor_maintenance',
  'operations',
  'operation_inputs',
  'inventory_purchases',
  'ap_ar_documents',
  'ap_ar_payments',
  'advance_allocations',
  'service_contracts',
  'service_contract_entries',
  'service_contract_line_items',
  'service_contract_payments',
  'cronograma_weeks',
  'cronograma_entries',
  'rainfall_records',
  'jornaleros',
  'exchange_rates',
  'scheduled_user_deletions',
] as const;

export type TableName = typeof TABLES_TO_EXPORT[number];
