-- RLS Fix 2: Restore admin and accountant SELECT policies for payroll_snapshots.
-- In migration 20260405123942 the following were dropped without replacement:
--   "Admins have full access to payroll snapshots"
--   "Accountants can view payroll snapshots"
-- Only "Management full access payroll snapshots" survived (it was re-created in the same migration).
-- payroll_snapshots contains sensitive payroll data; viewer/supervisor access is intentionally excluded.

-- Admin full access (SELECT + DML)
CREATE POLICY "entity_admin_payroll_snapshots" ON public.payroll_snapshots FOR ALL TO authenticated
  USING (public.has_role_for_entity(auth.uid(), 'admin'::app_role, entity_id))
  WITH CHECK (public.has_role_for_entity(auth.uid(), 'admin'::app_role, entity_id));

-- Accountants can view payroll snapshots (read-only — snapshots are generated by RPCs)
CREATE POLICY "entity_accountant_payroll_snapshots" ON public.payroll_snapshots FOR SELECT TO authenticated
  USING (public.has_role_for_entity(auth.uid(), 'accountant'::app_role, entity_id));
